---
functional:
  - Пользователь должен иметь возможность купить сертификат
  - Пользователь должен иметь возможность посмотреть информацию о каждом ресторане, подключенным к программе
  - Пользователь должен иметь возможность выбрать город
  - Пользователь должен иметь возможность 
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - 
